<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['multiwan_app_description'] = 'Aplikacja Multi-WAN pozwala na podłączenie do Twojego systemu wielu łącz internetowych. Multi-WAN oferuje wiele dobrego dla środowisk wymagających niezawodnego połączenia, włączając w to równoważenie obciążenia, segregację ruchu i automatyczne przełączanie się łącza, w przypadku awarii jednego z nich.';
$lang['multiwan_app_name'] = 'Multi-WAN';
$lang['multiwan_backup'] = 'Backup';
$lang['multiwan_destination_port_rule'] = 'Reguła dla portu docelowego';
$lang['multiwan_destination_port_rules'] = 'Reguły dla portu docelowego';
$lang['multiwan_in_use'] = 'W użyciu';
$lang['multiwan_multiwan'] = 'Multi-WAN';
$lang['multiwan_multiwan_status'] = 'Stan Multi-WAN';
$lang['multiwan_network_status'] = 'Stan sieci';
$lang['multiwan_offline'] = 'Offline';
$lang['multiwan_online'] = 'Online';
$lang['multiwan_primary'] = 'Primary';
$lang['multiwan_primary_or_backup'] = 'Primary or backup';
$lang['multiwan_source_based_route'] = 'Trasa oparta na lokalizacji źródłowej';
$lang['multiwan_source_based_routes'] = 'Trasy oparte na lokalizacji źródłowej';
$lang['multiwan_weight'] = 'Waga';
$lang['multiwan_weight_invalid'] = 'Podana waga dla Multi-WAN jest nieprawidłowa';
$lang['multiwan_weight_out_of_range'] = 'Podana waga Multi-WAN jest poza zakresem.';
